#!/usr/bin/env bash
# make-submission.sh — derive the ANONYMIZED ICFP 2027 submission source from
# the repository's paper, and verify the derivation.
#
#   input : docs/research/withe-paper.md
#           (deliberately carries provenance — the artifact tag and the
#           evidence-script names — because the repo is where a reader
#           reproduces the work)
#   output: docs/research/submission/withe-paper-submission.md
#           (fully double-blind: no artifact tags, no evidence-script names,
#           no repository URL/name, no author name.  §6.7's AI-use disclosure
#           and third-party citation URLs are KEPT.)
#
# The derivation is one-way and re-runnable: it always reads the source and
# regenerates the output, so after editing the paper you just re-run this
# script; two runs produce a byte-identical output.  The script VERIFIES
# ITSELF after writing and exits nonzero on any failure — an export that
# silently lags the source is worse than none.
#
# What is neutralized vs kept, and why:
#   * Every `withe-*` token (artifact tags, evidence-script names, the
#     companion-survey filename) is neutralized: the repository name survives
#     in the source only inside these tokens, and a reviewer could look a
#     tag or filename up.  The LANGUAGE name "Withe" is the paper's subject
#     and is deliberately NOT denied (it does not occur standalone in the
#     source; every occurrence is a hyphenated provenance token).
#   * Artifact-layout paths that name only the artifact's own directories
#     (elm-compiler/…, lean/…, tests/elm-fixtures/…, src/effectloop.zig,
#     docs/research/row-gadt*.md) are KEPT: they describe the supplementary
#     artifact a reviewer receives at submission time and name no owner,
#     repository, tag or author — stripping them would cost the paper's
#     reproducibility story for no anonymity gain.
#   * §6.7 (the ACM-required AI-use disclosure) and third-party citation URLs
#     (e.g. github.com/ocaml/ocaml/issues/5724) are KEPT.

set -euo pipefail
cd "$(dirname "$0")/.."

SRC="docs/research/withe-paper.md"
OUT="docs/research/submission/withe-paper-submission.md"

mkdir -p "$(dirname "$OUT")"

python3 - "$SRC" "$OUT" <<'PY'
import re
import sys
from pathlib import Path

src_path, out_path = sys.argv[1], sys.argv[2]
src = Path(src_path).read_text(encoding="utf-8")

# Ordered substitution rules (exact strings, most specific first; phrase
# rules precede the token rules they subsume).
RULES = [
    # §6.7: without the phrase rule the token rule would read
    # "the recount script (the recount script)".
    ("the recount script\n(`tools/withe-recount-runTask.sh`)", "the recount script"),
    ("`tools/withe-numbers.sh`", "the artifact's verification script"),
    ("`tools/withe-recount-runTask.sh`", "the recount script"),
    ("`tools/withe-corpus-baseline.sha256`", "the committed corpus manifest"),
    ("The artifact tag `withe-paper-artifact-1`", "The frozen artifact tag"),
    ("`withe-artifact-eval-1`", "the frozen artifact tag"),
    ("(`docs/research/withe-related-work.md`, which is the bibliography's source)",
     "(the companion document that is the bibliography's source)"),
    ("is the companion\n`docs/research/withe-related-work.md`)", "is the companion\nsurvey)"),
    (" (`docs/research/withe-related-work.md`)", ""),
    ("https://github.com/jmars/withe", "the artifact repository"),
    ("fixpoint-linux/withe", "the artifact repository"),
]

out = src
total = 0
print("substitutions (count  pattern -> replacement):")
for old, new in RULES:
    n = out.count(old)
    out = out.replace(old, new)
    total += n
    print(f"  {n:2d}  {old!r} -> {new!r}")

# Catch-all for any future backticked `withe-*` / `tools/withe-*` token the
# rules above do not name yet.  Expected to fire zero times at this HEAD;
# when it fires, add a specific rule above so the prose reads well.
def generic(m):
    tok = m.group(0)
    if "artifact" in tok:
        rep = "the frozen artifact tag"
    elif tok.endswith(".sh`"):
        rep = "the artifact's verification script"
    else:
        rep = "the artifact's supporting file"
    print(f"  WARNING: unhandled token {tok} -> {rep!r} (add a specific rule)")
    return rep

out, ncatch = re.subn(r"`(?:tools/)?withe-[A-Za-z0-9._-]+`", generic, out)
total += ncatch

# Generated-file marker (an HTML comment: invisible in rendered output).
BANNER = ("<!-- Generated by tools/make-submission.sh; do not edit by hand — "
          "edit the source paper and re-run the script. -->\n\n")
out = BANNER + out

Path(out_path).write_text(out, encoding="utf-8")

# ---- self-verification ------------------------------------------------------
failures = []

# 1. Every identifying string is ABSENT from the output.
DENY = [
    "withe-paper-artifact-1",        # artifact tag
    "withe-artifact-eval-1",         # artifact tag
    "tools/withe-numbers.sh",        # evidence script
    "tools/withe-recount-runTask.sh",# evidence script
    "tools/withe-corpus-baseline.sha256",
    "docs/research/withe-related-work.md",  # companion-survey filename (repo name)
    "https://github.com/jmars/withe",  # repository URL
    "fixpoint-linux/withe",          # the repository's pre-transfer path
    "fixpoint",                      # repository owner/org name
    "jmars",                         # repository owner's GitHub account name
    "jaye",                          # author's first name / e-mail local part
    "jaye.ch",                       # author's e-mail domain
    "Jaye Marshall",                 # author's full name
]
low = out.lower()
for s in DENY:
    if s.lower() in low:
        failures.append(f"identifying string PRESENT in output: {s!r}")
# Any hyphenated `withe-*` token (the repo name survives only in these).
for m in re.finditer(r"(?i)withe-[A-Za-z0-9._-]*", out):
    failures.append(f"withe-* token PRESENT in output: {m.group(0)!r}")

# 2. §6.7 and its AI-use disclosure are PRESENT.
KEEP = [
    "### 6.7 Provenance: AI assistance in building this artifact",
    "The ACM Policy on Authorship requires AI use that",
    "system is an author: under the ACM policy",
    "https://github.com/ocaml/ocaml/issues/5724",  # third-party citation kept
]
for s in KEEP:
    if s not in out:
        failures.append(f"required text ABSENT from output: {s!r}")

# 3. The output is not byte-identical to the input (the derivation did something).
if out == src:
    failures.append("output is byte-identical to the input")
if total == 0:
    failures.append("no substitutions were made")

if failures:
    print("\nSELF-VERIFICATION FAILED:", file=sys.stderr)
    for f in failures:
        print(f"  - {f}", file=sys.stderr)
    sys.exit(1)

print(f"\ntotal substitutions: {total}")
print("self-verification:")
print(f"  [PASS] {len(DENY)} identifying strings absent + no withe-* token remains")
print("  [PASS] §6.7 heading and AI-use disclosure present")
print("  [PASS] third-party citation URLs kept")
print(f"  [PASS] output differs from input ({total} substitutions)")
print(f"wrote {out_path}")
PY
